@extends('layouts.app')
@section('title', 'Pick it. Sell it. We handle the rest.')

@section('styles')
@vite('resources/css/views/welcome.css')
@endsection

@section('content')
<main class="landing">
    <section class="landing-hero">
        <div class="hero-stage">
            <div class="hero-stream hero-stream-left" aria-hidden="true"><div class="stream-track" id="leftTrack"></div></div>
            <div class="stage-center"><div class="landing-copy"><span class="eyebrow-pin">Philippine marketplace</span><h1 class="hero-headline">PICK IT.<br>SELL IT.<br><span>WE HANDLE THE REST.</span></h1><p class="landing-lede">PickSell connects buyers, sellers, and couriers through one marketplace - with a dedicated sorting center that keeps every order moving from click to doorstep.</p><div class="landing-actions"><a href="/shop" class="landing-action landing-primary">Browse products</a><a href="/register" class="landing-action landing-secondary">Join as buyer or seller</a></div></div></div>
            <div class="hero-stream hero-stream-right" aria-hidden="true"><div class="stream-track" id="rightTrack"></div></div>
        </div>
    </section>
    <div class="marquee" aria-hidden="true"><div class="marquee-track"><span>Buy with confidence</span><i></i><span>Sell with purpose</span><i></i><span>Discover local</span><i></i><span>Buy with confidence</span><i></i><span>Sell with purpose</span><i></i><span>Discover local</span><i></i></div></div>
    <section id="how-it-works" class="journey-section reveal"><div class="journey-heading"><div class="section-kicker">How PickSell works</div><h2 class="section-title">One marketplace, four hands, one delivery.</h2><p class="section-note">Every order moves through the same reliable path, sorted and tracked along the way.</p></div><div class="journey-grid"><article class="journey-card"><div class="journey-icon">▣</div><div class="journey-label">STEP 1</div><h3>Buyer</h3><p>Finds and orders a product from a verified seller.</p></article><article class="journey-card"><div class="journey-icon">▤</div><div class="journey-label">STEP 2</div><h3>Seller</h3><p>Packs the order and hands it off for pickup.</p></article><article class="journey-card journey-emphasis"><div class="journey-icon">↗</div><div class="journey-label">STEP 3</div><h3>Sorting Center</h3><p>PickSell routes the order to the right courier and destination.</p></article><article class="journey-card"><div class="journey-icon">⌁</div><div class="journey-label">STEP 4</div><h3>Courier</h3><p>Picks up from sorting and delivers it directly.</p></article></div></section>
    <div class="marquee" aria-hidden="true"><div class="marquee-track"><span>Radical trust</span><i></i><span>Effortless convenience</span><i></i><span>Maximum efficiency</span><i></i><span>Unwavering integrity</span><i></i><span>Radical trust</span><i></i><span>Effortless convenience</span><i></i><span>Maximum efficiency</span><i></i><span>Unwavering integrity</span><i></i></div></div>
    <section id="what-we-stand-for" class="promise-band reveal"><div class="promise-grid"><div><div class="section-kicker">What we stand for</div><h2>Built on five things we won't compromise on.</h2></div><div><div class="section-kicker">Our vision</div><h2>Empowering every Filipino to buy and sell with absolute confidence, fueled by a world-class logistics infrastructure.</h2></div><div class="promise-values"><article class="promise-value"><i>01</i><strong>Trust</strong><span>Verified sellers and secure transactions at every step.</span></article><article class="promise-value"><i>02</i><strong>Convenience</strong><span>Everything a buyer, seller, or courier needs in one place.</span></article><article class="promise-value"><i>03</i><strong>Efficiency</strong><span>A sorting center built to keep orders moving without delay.</span></article><article class="promise-value"><i>04</i><strong>Integrity</strong><span>Honest listings, fair pricing, and accountable partners.</span></article><article class="promise-value"><i>05</i><strong>Community</strong><span>Supporting local sellers and couriers building their livelihood.</span></article></div></div></section>
    <section class="category-section reveal"><div class="category-heading"><div><div class="section-kicker">What you'll find</div><h2 class="section-title">A marketplace built for everyday categories.</h2><p class="section-note">Picksell is preparing for launch across the categories Filipino shoppers buy most.</p></div></div><div class="category-grid"><a href="/shop?cat=electronics" class="category-card"><span>▣</span><strong>Electronics</strong></a><a href="/shop?cat=fashion" class="category-card"><span>✦</span><strong>Fashion</strong></a><a href="/shop?cat=home" class="category-card"><span>⌂</span><strong>Home &amp; Garden</strong></a><a href="/shop?cat=pets" class="category-card"><span>♣</span><strong>Pet Supplies</strong></a><a href="/shop?cat=food" class="category-card"><span>≡</span><strong>Food &amp; Gourmet</strong></a><a href="/shop?cat=sports" class="category-card"><span>◈</span><strong>Sports &amp; Outdoors</strong></a><a href="/shop?cat=beauty" class="category-card"><span>♡</span><strong>Beauty</strong></a><a href="/shop?cat=office" class="category-card"><span>▤</span><strong>Office &amp; School</strong></a></div></section>
    <section id="why-it-works" class="trust-section reveal"><div class="trust-heading"><div class="section-kicker">Why it works</div><h2 class="section-title">Confidence built into every order.</h2><p class="section-note">Every part of the journey is designed to keep buyers, sellers, and couriers protected.</p></div><div class="trust-grid"><article class="trust-card"><div class="trust-icon">✓</div><strong class="trust-card-title">Verified Sellers</strong><p class="trust-card-desc">Sellers go through identity and business checks before listing.</p></article><article class="trust-card"><div class="trust-icon">▣</div><strong class="trust-card-title">Secure Checkout</strong><p class="trust-card-desc">Payments are handled through clear and protected checkout steps.</p></article><article class="trust-card"><div class="trust-icon">⌂</div><strong class="trust-card-title">Buyer Protection</strong><p class="trust-card-desc">Support is available if an order does not arrive as described.</p></article><article class="trust-card"><div class="trust-icon">◷</div><strong class="trust-card-title">Order Tracking</strong><p class="trust-card-desc">Follow an order from packing to sorting to your doorstep.</p></article><article class="trust-card"><div class="trust-icon">↗</div><strong class="trust-card-title">Integrated Sorting</strong><p class="trust-card-desc">A dedicated center routes every order to the right courier.</p></article><article class="trust-card"><div class="trust-icon">→</div><strong class="trust-card-title">Reliable Delivery</strong><p class="trust-card-desc">Couriers pick up straight from sorting for a direct route.</p></article></div></section>
    <section class="landing-section reveal"><div class="section-heading"><div><div class="section-kicker">Hand-picked for you</div><h2 class="section-title">Featured <span class="blade-inline-1">products.</span></h2></div><p class="section-note">A few good things to get you started. There is more waiting in the marketplace.</p></div><div class="landing-products">@forelse($featuredProducts as $product)<article class="landing-product"><div class="landing-product-image"><img src="{{ Storage::url($product->image) }}" alt="{{ $product->name }}" loading="lazy"><div class="landing-product-details"><small>{{ $product->category }}</small><strong>{{ $product->name }}</strong><span>₱{{ number_format($product->effective_price, 2) }} · Limited-time offer</span></div></div><div class="landing-product-body"><strong>{{ $product->name }}</strong><span class="landing-product-price">₱{{ number_format($product->effective_price, 2) }}</span>@if($product->discount > 0)<span class="landing-product-old">₱{{ number_format($product->price, 2) }}</span>@endif<a href="/shop?cat={{ urlencode(strtolower($product->category)) }}" class="landing-product-link">View product <span aria-hidden="true">→</span></a></div></article>@empty<p class="section-note">Featured products are coming soon.</p>@endforelse</div></section>
    <section class="browse-cta reveal"><div><div class="section-kicker">Ready to explore?</div><h2>Browse the marketplace before you sign in.</h2><p>Discover available products and categories without getting stuck on the landing page.</p></div><a href="/shop" class="landing-action landing-primary">Go to shop</a></section>
    <section id="get-started" class="cta-section reveal"><div class="section-kicker blade-inline-2">Your next move starts here</div><h2>Be part of PickSell.</h2><p>Enter your email once and continue with a prefilled buyer or seller application.</p><form class="cta-form" action="/register" method="GET" data-normalize-email style="position:relative;z-index:3;pointer-events:auto"><input type="email" name="email" placeholder="Enter your email address" aria-label="Email address" required style="color:#1b1b1b!important;background:#fff!important;caret-color:#e8472a!important;-webkit-text-fill-color:#1b1b1b!important"><button type="submit">Continue sign up</button></form></section>
</main>
@endsection

@section('scripts')
@vite('resources/js/views/welcome.js')
@endsection
