import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';
import { bunny } from 'laravel-vite-plugin/fonts';
import tailwindcss from '@tailwindcss/vite';

export default defineConfig({
    plugins: [
        laravel({
            input: [
                'resources/css/app.css',
                'resources/css/layouts/app.css',
                'resources/css/pages/login.css',
                'resources/css/components/dashboard-clock.css',
                'resources/js/app.js',
                'resources/js/pages/login.js',
                'resources/js/components/dashboard-clock.js',
                'resources/js/components/search-suggestions.js',
                'resources/js/components/profile-address.js',
                'resources/js/components/navbar.js',
                'resources/js/components/form-behaviors.js',
                'resources/js/views/buyer-cart.js',
                'resources/js/views/admin-dashboard.js',
                'resources/js/views/admin-commission.js',
                'resources/js/views/admin-reports.js',
                'resources/js/views/auth-register-wizard.js',
                'resources/js/views/logistics-branches.js',
                'resources/css/views/admin-application-detail.css',
                'resources/css/views/admin-commission.css',
                'resources/css/views/admin-complaint-detail.css',
                'resources/css/views/admin-complaints.css',
                'resources/css/views/admin-compliance.css',
                'resources/css/views/admin-dashboard.css',
                'resources/css/views/admin-logistics.css',
                'resources/css/views/admin-products.css',
                'resources/css/views/admin-registrations.css',
                'resources/css/views/admin-reports.css',
                'resources/css/views/admin-settings.css',
                'resources/css/views/admin-users.css',
                'resources/css/views/buyer-cart.css',
                'resources/css/views/buyer-home.css',
                'resources/css/views/courier-account.css',
                'resources/css/views/courier-chat.css',
                'resources/css/views/courier-dashboard.css',
                'resources/css/views/courier-reports.css',
                'resources/css/views/logistics-account.css',
                'resources/css/views/logistics-account-template.css',
                'resources/css/views/logistics-applications.css',
                'resources/css/views/logistics-branch-edit.css',
                'resources/css/views/logistics-dashboard.css',
                'resources/css/views/logistics-module.css',
                'resources/css/views/logistics-parcels.css',
                'resources/css/views/seller-dashboard.css',
                'resources/css/views/seller-inventory.css',
                'resources/css/views/seller-order-detail.css',
                'resources/css/views/seller-orders.css',
                'resources/css/views/seller-reports.css',
                'resources/js/views/admin-chat.js',
                'resources/js/views/admin-compliance.js',
                'resources/js/views/admin-layout.js',
                'resources/js/views/auth-register.js',
                'resources/js/views/buyer-chat.js',
                'resources/js/views/buyer-layout.js',
                'resources/js/views/buyer-orders.js',
                'resources/js/views/buyer-product-detail.js',
                'resources/js/views/logistics-layout.js',
                'resources/js/views/seller-chat.js',
                'resources/js/views/seller-dashboard.js',
                'resources/js/views/seller-inventory.js',
                'resources/js/views/seller-layout.js',
                'resources/js/views/seller-orders.js',
                'resources/js/views/seller-reports.js',
                'resources/js/views/welcome.js',
                'resources/js/views/pages-contact.js',
                'resources/css/views/admin-account.css',
                'resources/css/views/admin-chat.css',
                'resources/css/views/admin-layout.css',
                'resources/css/views/auth-forgot-password.css',
                'resources/css/views/auth-register.css',
                'resources/css/views/auth-reset-password.css',
                'resources/css/views/buyer-account.css',
                'resources/css/views/buyer-chat.css',
                'resources/css/views/buyer-layout.css',
                'resources/css/views/buyer-orders.css',
                'resources/css/views/buyer-product-detail.css',
                'resources/css/views/buyer-storefront.css',
                'resources/css/views/courier-layout.css',
                'resources/css/views/dashboard.css',
                'resources/css/views/logistics-branches.css',
                'resources/css/views/logistics-layout.css',
                'resources/css/views/pages-about.css',
                'resources/css/views/pages-contact.css',
                'resources/css/views/pages-shop.css',
                'resources/css/views/partials-footer.css',
                'resources/css/views/partials-navbar.css',
                'resources/css/views/partials-pagination-styles.css',
                'resources/css/views/partials-profile-address-script.css',
                'resources/css/views/partials-search-suggestions.css',
                'resources/css/views/seller-account.css',
                'resources/css/views/seller-chat.css',
                'resources/css/views/seller-layout.css',
                'resources/css/views/welcome.css',
            ],
            refresh: true,
            fonts: [
                bunny('Instrument Sans', {
                    weights: [400, 500, 600],
                    optimizedFallbacks: false,
                }),
            ],
        }),
        tailwindcss(),
    ],
    server: {
        watch: {
            ignored: ['**/storage/framework/views/**'],
        },
    },
});
