<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
    body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #2D2D2D; margin: 0; padding: 20px; }
    .header { border-bottom: 3px solid #E8472A; padding-bottom: 12px; margin-bottom: 20px; display: flex; justify-content: space-between; align-items: flex-end; }
    .logo { font-size: 22px; font-weight: bold; color: #E8472A; }
    .logo span { color: #2D2D2D; }
    .report-title { font-size: 16px; font-weight: bold; margin-bottom: 4px; }
    .report-meta { font-size: 11px; color: #888; }
    .section-title { font-size: 13px; font-weight: bold; background: #f5f0e8; padding: 6px 10px; border-left: 4px solid #E8472A; margin: 16px 0 8px; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 16px; }
    th { background: #2D2D2D; color: #fff; padding: 7px 10px; text-align: left; font-size: 11px; }
    td { padding: 6px 10px; border-bottom: 1px solid #f0ebe0; font-size: 11px; }
    tr:nth-child(even) td { background: #fafaf8; }
    .stat-row { display: flex; gap: 12px; margin-bottom: 16px; }
    .stat-box { flex: 1; border: 1px solid #e8e2d8; border-radius: 6px; padding: 10px; text-align: center; }
    .stat-num { font-size: 18px; font-weight: bold; color: #E8472A; }
    .stat-label { font-size: 10px; color: #888; margin-top: 2px; }
    .footer { border-top: 1px solid #e8e2d8; margin-top: 20px; padding-top: 10px; font-size: 10px; color: #aaa; text-align: center; }
    .coral { color: #E8472A; font-weight: bold; }
</style>
</head>
<body>
<div class="header">
    <div>
        <div class="logo">Pick<span>Sell</span></div>
        <div style="font-size:10px;color:#888;">Admin Panel — Official Report</div>
    </div>
    <div style="text-align:right;">
        <div class="report-title">{{ $type === 'sales' ? 'Sales Summary Report' : 'Commission Report' }}</div>
        <div class="report-meta">Period: {{ \Carbon\Carbon::parse($from)->format('M d, Y') }} — {{ \Carbon\Carbon::parse($to)->format('M d, Y') }}</div>
        <div class="report-meta">Generated: {{ now()->format('M d, Y h:i A') }}</div>
    </div>
</div>

<!-- Summary -->
<div class="section-title">Summary</div>
<table>
    <tr>
        <th>Total Sales</th><th>Total Orders</th><th>Total Commission</th><th>New Buyers</th><th>New Sellers</th>
    </tr>
    <tr>
        <td class="coral">₱{{ number_format($data['total_sales']) }}</td>
        <td>{{ $data['total_orders'] }}</td>
        <td class="coral">₱{{ number_format($data['total_commission']) }}</td>
        <td>{{ $data['new_buyers'] }}</td>
        <td>{{ $data['new_sellers'] }}</td>
    </tr>
</table>

<!-- Top Sellers -->
<div class="section-title">Top Sellers Performance</div>
<table>
    <thead><tr><th>#</th><th>Seller</th><th>Total Sales</th><th>Orders</th><th>Commission (10%)</th></tr></thead>
    <tbody>
    @foreach($data['top_sellers'] as $i => $s)
    <tr>
        <td>{{ $i + 1 }}</td>
        <td>{{ $s['name'] }}</td>
        <td>₱{{ number_format($s['sales']) }}</td>
        <td>{{ $s['orders'] }}</td>
        <td class="coral">₱{{ number_format($s['commission']) }}</td>
    </tr>
    @endforeach
    </tbody>
</table>

@if($type === 'commission')
<div class="section-title">Commission Breakdown</div>
<table>
    <thead><tr><th>Week</th><th>Sales</th><th>Commission</th></tr></thead>
    <tbody>
    @foreach($data['months'] as $i => $month)
    <tr>
        <td>{{ $month }}</td>
        <td>₱{{ number_format($data['monthly_sales'][$i]) }}</td>
        <td class="coral">₱{{ number_format($data['monthly_sales'][$i] * 0.10) }}</td>
    </tr>
    @endforeach
    </tbody>
</table>
@endif

<div class="footer">
    This report was automatically generated by PickSell Admin Panel. &copy; {{ date('Y') }} PickSell. All rights reserved.
</div>
</body>
</html>
