<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Seller Earnings {{ $from }} to {{ $to }}</title>
    <style>
        @page { margin: 34px 38px; }
        * { box-sizing: border-box; }
        body { margin: 0; color: #1f2937; font-family: DejaVu Sans, Arial, sans-serif; font-size: 9px; }
        .header { border-bottom: 3px solid #e8472a; padding-bottom: 12px; }
        .brand { color: #e8472a; font-size: 20px; font-weight: 800; }
        .brand span { color: #1f2937; }
        h1 { margin: 7px 0 3px; font-size: 17px; }
        .period,.note { color: #6b7280; }
        .note { margin-top: 5px; }
        .summary { width: 100%; margin: 14px 0; border-collapse: separate; border-spacing: 6px; }
        .summary td { width: 33.33%; padding: 10px; border: 1px solid #e5e7eb; background: #f9fafb; }
        .label { color: #6b7280; font-size: 8px; text-transform: uppercase; }
        .value { margin-top: 5px; font-size: 14px; font-weight: 800; }
        table.orders { width: 100%; border-collapse: collapse; }
        .orders th { padding: 7px 6px; background: #f3f4f6; color: #4b5563; font-size: 7px; text-align: left; text-transform: uppercase; }
        .orders td { padding: 7px 6px; border-bottom: 1px solid #e5e7eb; }
        .orders th:not(:first-child), .orders td:not(:first-child) { text-align: right; }
        .empty { padding: 18px; color: #6b7280; text-align: center; }
        .footer { margin-top: 20px; padding-top: 8px; border-top: 1px solid #d1d5db; color: #6b7280; font-size: 8px; text-align: center; }
    </style>
</head>
<body>
    <div class="header">
        <div class="brand">Pick<span>Sell</span></div>
        <h1>Seller Commission &amp; Earnings</h1>
        <div class="period">Reporting period: {{ \Carbon\Carbon::parse($from)->format('M d, Y') }} to {{ \Carbon\Carbon::parse($to)->format('M d, Y') }}</div>
        <div class="note">Informational report only. This document does not initiate or confirm a payout.</div>
    </div>
    <table class="summary">
        <tr>
            <td><div class="label">Total gross sales</div><div class="value">PHP {{ number_format($totalSales, 2) }}</div></td>
            <td><div class="label">Total commission</div><div class="value">-PHP {{ number_format($totalCommission, 2) }}</div></td>
            <td><div class="label">Net earnings</div><div class="value">PHP {{ number_format($totalNetEarnings, 2) }}</div></td>
        </tr>
    </table>
    @if($orders->isEmpty())
        <div class="empty">No completed orders in this period.</div>
    @else
        <table class="orders">
            <thead>
                <tr><th>Order / date</th><th>Gross (PHP)</th><th>Rate</th><th>Commission (PHP)</th><th>Net (PHP)</th><th>Status</th></tr>
            </thead>
            <tbody>
            @foreach($orders as $order)
                <tr>
                    <td>{{ $order['order_number'] }}<br>{{ $order['created_at']->format('M d, Y') }}</td>
                    <td>{{ number_format($order['amount'], 2) }}</td>
                    <td>{{ number_format($order['commission_rate'], 2) }}%</td>
                    <td>-{{ number_format($order['commission'], 2) }}</td>
                    <td>{{ number_format($order['net_earnings'], 2) }}</td>
                    <td>{{ ucfirst($order['status']) }}</td>
                </tr>
            @endforeach
            </tbody>
        </table>
    @endif
    <div class="footer">Generated by PickSell Seller Panel on {{ now()->format('M d, Y h:i A') }}</div>
</body>
</html>
