<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Seller Report {{ $from }} to {{ $to }}</title>
    <style>
        @page { margin: 34px 38px; }
        * { box-sizing: border-box; }
        body { margin: 0; color: #1f2937; font-family: DejaVu Sans, Arial, sans-serif; font-size: 10px; }
        .header { border-bottom: 3px solid #e8472a; padding-bottom: 14px; }
        .brand { color: #e8472a; font-size: 22px; font-weight: 800; letter-spacing: -1px; }
        .brand span { color: #1f2937; }
        .report-title { margin-top: 6px; font-size: 18px; font-weight: 700; }
        .period { margin-top: 4px; color: #6b7280; font-size: 10px; }
        .seller { margin-top: 12px; color: #4b5563; }
        .summary { width: 100%; border-collapse: separate; border-spacing: 8px; margin: 15px -8px 12px; }
        .summary td { width: 25%; padding: 11px; border: 1px solid #e5e7eb; border-radius: 7px; background: #f9fafb; }
        .summary-label { color: #6b7280; font-size: 8px; text-transform: uppercase; letter-spacing: .6px; }
        .summary-value { margin-top: 5px; color: #e8472a; font-size: 15px; font-weight: 800; }
        .section-title { margin: 18px 0 7px; color: #e8472a; font-size: 11px; font-weight: 800; text-transform: uppercase; letter-spacing: .7px; }
        table.data { width: 100%; border-collapse: collapse; }
        .data th { padding: 7px 8px; background: #f3f4f6; color: #4b5563; font-size: 8px; text-align: left; text-transform: uppercase; letter-spacing: .4px; }
        .data td { padding: 7px 8px; border-bottom: 1px solid #e5e7eb; }
        .data th:not(:first-child), .data td:not(:first-child) { text-align: right; }
        .empty { padding: 16px; color: #6b7280; text-align: center; }
        .footer { margin-top: 26px; padding-top: 10px; border-top: 1px solid #d1d5db; color: #6b7280; font-size: 8px; text-align: center; }
    </style>
</head>
<body>
    <div class="header">
        <div class="brand">Pick<span>Sell</span></div>
        <div class="report-title">Seller Financial &amp; Performance Report</div>
        <div class="period">Reporting period: {{ \Carbon\Carbon::parse($from)->format('M d, Y') }} to {{ \Carbon\Carbon::parse($to)->format('M d, Y') }}</div>
        <div class="seller">Prepared for: {{ auth()->user()->business_name ?? auth()->user()->full_name }}</div>
    </div>

    <table class="summary">
        <tr>
            <td><div class="summary-label">Total sales</div><div class="summary-value">PHP {{ number_format($totalSales, 2) }}</div></td>
            <td><div class="summary-label">Completed orders</div><div class="summary-value">{{ $totalOrders }}</div></td>
            <td><div class="summary-label">Net profit</div><div class="summary-value">PHP {{ number_format($totalProfit, 2) }}</div></td>
            <td><div class="summary-label">Average order</div><div class="summary-value">PHP {{ $totalOrders ? number_format($totalSales / $totalOrders, 2) : '0.00' }}</div></td>
        </tr>
    </table>

    <div class="section-title">Daily sales</div>
    @if(count($days))
    <table class="data">
        <thead><tr><th>Date</th><th>Sales</th></tr></thead>
        <tbody>
        @foreach($days as $index => $day)
            <tr><td>{{ $day }}</td><td>PHP {{ number_format($dailySales[$index] ?? 0, 2) }}</td></tr>
        @endforeach
        </tbody>
    </table>
    @else
        <div class="empty">No sales data for this period.</div>
    @endif

    <div class="section-title">Top products</div>
    @if($topProducts->isNotEmpty())
    <table class="data">
        <thead><tr><th>Product</th><th>Orders</th><th>Sales</th></tr></thead>
        <tbody>
        @foreach($topProducts as $product)
            <tr><td>{{ $product['name'] }}</td><td>{{ $product['count'] }}</td><td>PHP {{ number_format($product['sales'], 2) }}</td></tr>
        @endforeach
        </tbody>
    </table>
    @else
        <div class="empty">No product data for this period.</div>
    @endif

    <div class="footer">Generated by PickSell Seller Panel on {{ now()->format('M d, Y h:i A') }}</div>
</body>
</html>
