<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>PickSell Logistics - @yield('title')</title>
    <style>
        :root { --coral:#E8472A; --charcoal:#2D2D2D; --sidebar-w:240px; }
        * { box-sizing:border-box; } body, body *, body *::before, body *::after { transition:background-color .35s ease, color .35s ease, border-color .35s ease, box-shadow .35s ease; } body { margin:0; font-family:'Segoe UI',sans-serif; background:#f4f4f4; color:#2d2d2d; }
        body.dark { background:#111;color:#e5e7eb; } body.dark .main, body.dark .topbar { background:#111;border-color:#2a2a2a; } body.dark .card, body.dark .stat { background:#1e1e1e;border-color:#2a2a2a;color:#e5e7eb; } body.dark .card-header, body.dark td, body.dark th { border-color:#2a2a2a; } body.dark .filter-select, body.dark .form-control { background:#2a2a2a;border-color:#3a3a3a;color:#f3f4f6; }
        a { color:inherit; text-decoration:none; }
        .sidebar { width:var(--sidebar-w); background:var(--charcoal); color:#fff; position:fixed; inset:0 auto 0 0; display:flex; flex-direction:column; z-index:20; overflow:hidden; transition:width .25s ease; }.sidebar.mini { width:64px; }
        .sidebar-logo { padding:1rem 1.2rem; border-bottom:1px solid #3a3a3a; min-height:74px;display:flex;align-items:center;justify-content:space-between;gap:.5rem; }.brand { color:var(--coral);font-size:1.35rem;font-weight:800;white-space:nowrap; }.brand span { color:#fff; }.sidebar-subtitle { color:#888;font-size:.68rem;text-transform:uppercase;letter-spacing:.08em;margin-top:.15rem;white-space:nowrap; }.hamburger { background:none;border:0;color:#aaa;cursor:pointer;padding:.3rem;border-radius:6px;display:flex;align-items:center;justify-content:center;flex-shrink:0; }.hamburger:hover { color:#fff;background:#3a3a3a; }.sidebar.mini .sidebar-logo-text,.sidebar.mini .nav-label,.sidebar.mini .nav-text,.sidebar.mini .sidebar-footer-text { display:none; }.sidebar.mini .sidebar-logo { justify-content:center;padding:1rem .7rem; }.sidebar.mini .hamburger { display:flex; }
        .sidebar-nav { flex:1;padding:1rem 0;overflow-y:auto; }.nav-label { color:#777;font-size:.68rem;font-weight:700;text-transform:uppercase;letter-spacing:.08em;padding:.8rem 1.2rem .35rem; }.nav-item { display:flex;align-items:center;gap:.7rem;padding:.7rem 1.2rem;color:#bbb;font-size:.88rem;white-space:nowrap; }.nav-item:hover { background:#3a3a3a;color:#fff; }.nav-item.active { background:rgba(232,71,42,.15);color:#ff8068;border-right:3px solid var(--coral); }.nav-icon { width:20px;text-align:center;flex-shrink:0; }.sidebar.mini .nav-item { justify-content:center;padding:.7rem 0; }.sidebar.mini .nav-item.active { border-right:0;border-left:3px solid var(--coral); }.sidebar-footer { padding:1rem;border-top:1px solid #3a3a3a;background:var(--charcoal); }.staff-card { background:#1f1f21;border:1px solid #363639;border-radius:14px;padding:.65rem .7rem;box-shadow:0 8px 22px rgba(0,0,0,.12);transition:border-color .25s,background .25s,transform .25s; }.staff-card:hover { border-color:#4a4a4d;background:#242426;transform:translateY(-1px); }.staff-info { display:flex;align-items:center;gap:.65rem; }.staff-avatar { width:36px;height:36px;background:#f4f1eb;border:2px solid #4a4a4d;border-radius:50%;display:flex;align-items:center;justify-content:center;font-weight:800;font-size:.88rem;flex-shrink:0;color:var(--charcoal); }.staff-text { flex:1;min-width:0;overflow:hidden; }.staff-name { color:#f4f1eb;font-size:.78rem;font-weight:700;white-space:nowrap;overflow:hidden;text-overflow:ellipsis; }.staff-role { color:#99999f;font-size:.68rem;margin-top:.12rem;white-space:nowrap; }.sidebar.mini .staff-text,.sidebar.mini .btn-logout { display:none; }.sidebar.mini .staff-card { padding:.5rem;display:flex;justify-content:center; }.btn-logout { background:transparent;border:1px solid #454549;color:#aaa;border-radius:8px;padding:.42rem .48rem;cursor:pointer;display:flex;align-items:center;justify-content:center;flex-shrink:0;transition:background .2s,border-color .2s,color .2s,transform .2s; }.btn-logout:hover { background:var(--coral);border-color:var(--coral);color:#fff;transform:translateX(2px);box-shadow:0 5px 12px rgba(232,71,42,.28); }
        .main { margin-left:var(--sidebar-w);min-height:100vh;transition:margin-left .25s ease; }.main.mini { margin-left:64px; }.topbar { height:60px;background:#fff;border-bottom:1px solid #e8e2d8;padding:0 1.5rem;display:flex;align-items:center;justify-content:space-between;position:sticky;top:0;z-index:10; }.topbar-title { font-size:1.1rem;font-weight:700; }.topbar-tools { display:flex;align-items:center;gap:1rem; }.dm-toggle { width:38px;height:38px;border:0;border-radius:50%;background:var(--charcoal);color:#fff;cursor:pointer;display:flex;align-items:center;justify-content:center; }.dm-toggle:hover { background:var(--coral); }.page { max-width:1400px;margin:auto;padding:1.5rem; }
        .card { background:#fff;border:1px solid #e8e2d8;border-radius:10px;margin-bottom:1.2rem;overflow:hidden; }.card-header { padding:1rem 1.2rem;border-bottom:1px solid #f0ebe0;display:flex;justify-content:space-between;align-items:center;gap:1rem;flex-wrap:wrap; }.card-body { padding:1.2rem; }.card-title { font-weight:700; }
        .stats { display:grid;grid-template-columns:repeat(4,1fr);gap:1rem;margin-bottom:1.2rem; }.stat { background:#fff;border:1px solid #e8e2d8;border-radius:10px;padding:1rem; }.stat strong { display:block;font-size:1.5rem;color:var(--coral); }.stat span { color:#888;font-size:.8rem; }
        table { width:100%;border-collapse:collapse;font-size:.85rem; } th { text-align:left;color:#888;font-size:.7rem;text-transform:uppercase;padding:.65rem;border-bottom:1px solid #eee; } td { padding:.75rem .65rem;border-bottom:1px solid #f3f0eb;vertical-align:middle; }
        .btn { border:0;border-radius:6px;padding:.48rem .8rem;font-weight:600;cursor:pointer;font-size:.8rem; }.btn-coral { background:var(--coral);color:#fff; }.btn-success { background:#16a34a;color:#fff; }.btn-outline { border:1px solid #d8d0c3;background:#fff;color:#555; }.filter-select,.form-control { padding:.5rem .65rem;border:1px solid #d8d0c3;border-radius:6px;background:#fff; }.badge { display:inline-block;border-radius:999px;padding:.2rem .55rem;font-size:.7rem;font-weight:700;text-transform:uppercase; }.badge-pending { background:#fff8e1;color:#b45309; }.badge-approved { background:#f0fdf4;color:#16a34a; }.badge-disapproved { background:#fef2f0;color:#dc2626; }.badge-shipped { background:#eff6ff;color:#2563eb; }.badge-completed { background:#f0fdf4;color:#16a34a; }.alert { padding:.8rem 1rem;border-radius:7px;margin-bottom:1rem; }.alert-success { background:#f0fdf4;color:#166534;border:1px solid #bbf7d0; }.alert-error { background:#fef2f2;color:#991b1b;border:1px solid #fecaca; }
        @media(max-width:700px) { .sidebar { width:64px; }.sidebar-logo { padding:.9rem .5rem;text-align:center; }.brand { font-size:1rem; }.sidebar-subtitle,.nav-label,.nav-text,.sidebar-footer-text { display:none; }.hamburger { display:flex; }.nav-item { justify-content:center;padding:.75rem 0; }.nav-item.active { border-right:0;border-left:3px solid var(--coral); }.main { margin-left:64px; }.topbar { padding:0 1rem; }.page { padding:1rem; }.stats { grid-template-columns:repeat(2,1fr); } }
    </style>
    @include('partials.pagination-styles')
</head>
<body>
<aside class="sidebar">
    <div class="sidebar-logo"><div class="sidebar-logo-text"><a class="brand" href="{{ route('logistics.dashboard') }}">Pick<span>Sell</span></a><div class="sidebar-subtitle">Logistics Panel</div></div><button class="hamburger" type="button" onclick="toggleSidebar()" title="Collapse sidebar"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24" aria-hidden="true"><path d="M4 6h16M4 12h16M4 18h16"/></svg></button></div>
    <nav class="sidebar-nav">
        <div class="nav-label">Overview</div>
        <a class="nav-item {{ request()->routeIs('logistics.dashboard') ? 'active' : '' }}" href="{{ route('logistics.dashboard') }}"><span class="nav-icon">▦</span><span class="nav-text">Dashboard</span></a>
        <div class="nav-label">Operations</div>
        <a class="nav-item {{ request()->routeIs('logistics.applications') ? 'active' : '' }}" href="{{ route('logistics.applications') }}"><span class="nav-icon">♙</span><span class="nav-text">Courier Applications</span></a>
        <a class="nav-item {{ request()->routeIs('logistics.parcels') ? 'active' : '' }}" href="{{ route('logistics.parcels') }}"><span class="nav-icon">▣</span><span class="nav-text">Sorting Center</span></a>
    </nav>
    <div class="sidebar-footer"><div class="staff-card"><div class="staff-info"><div class="staff-avatar">{{ strtoupper(substr(auth()->user()->first_name, 0, 1)) }}</div><div class="staff-text"><div class="staff-name">{{ auth()->user()->full_name }}</div><div class="staff-role">Logistics Staff</div></div><form method="POST" action="{{ route('logout') }}">@csrf<button class="btn-logout" type="submit" title="Log out"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 24 24"><path d="M17 7l-1.41 1.41L18.17 11H8v2h10.17l-2.58 2.58L17 17l5-5-5-5zM4 5h8V3H4c-1.1 0-2 0-2 2v14c0 1.1.9 2 2 2h8v-2H4V5z"/></svg></button></form></div></div></div>
</aside>
<div class="main" id="main"><header class="topbar"><div class="topbar-title">@yield('title')</div><div class="topbar-tools">@include('partials.dashboard-clock')<button class="dm-toggle" type="button" onclick="toggleDark()" title="Toggle dark mode">◐</button></div></header><main class="page">@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif @if($errors->any())<div class="alert alert-error">{{ $errors->first() }}</div>@endif @yield('content')</main></div>
<script>
function toggleSidebar() {
    document.querySelector('.sidebar').classList.toggle('mini');
    document.getElementById('main').classList.toggle('mini');
    localStorage.setItem('logisticsSidebarMini', document.querySelector('.sidebar').classList.contains('mini'));
}
function toggleDark() {
    document.body.classList.toggle('dark');
    localStorage.setItem('logisticsDark', document.body.classList.contains('dark'));
}
if (localStorage.getItem('logisticsSidebarMini') === 'true') { document.querySelector('.sidebar').classList.add('mini'); document.getElementById('main').classList.add('mini'); }
if (localStorage.getItem('logisticsDark') === 'true') document.body.classList.add('dark');
</script>
</body>
</html>
